package telasIniciais;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;
import javax.swing.JOptionPane;


public class telaLogin extends javax.swing.JFrame {

    /**
     * Creates new form telaLogin
     */
    public telaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("LOGIN");

        jLabel2.setText("usuario");

        jLabel3.setText("senha");

        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                    .addComponent(txtSenha)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnLogin)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String usuarioDigitado = txtUsuario.getText();
String senhaDigitada = txtSenha.getText();

// Validação básica se os campos estão vazios
if (usuarioDigitado.trim().isEmpty()) {
    JOptionPane.showMessageDialog(null, "Por favor, digite o usuário!");
} else if (senhaDigitada.trim().isEmpty()) {
    JOptionPane.showMessageDialog(null, "Por favor, digite a senha!");
} else {
    
    try {
        Connection conn = conexao.conexao.conectar();

        // SQL para buscar o usuário e a senha correspondentes
        String sqlBuscar = "select usuario, senha from usuarios where usuario = ?;";
        PreparedStatement stmtBuscar = conn.prepareStatement(sqlBuscar);
        stmtBuscar.setString(1, usuarioDigitado);
        
        ResultSet rs = stmtBuscar.executeQuery();

        // Verifica se encontrou o usuário no banco
        if (rs.next()) {
            String senhaDoBanco = rs.getString("senha");
            String usuarioDoBanco = rs.getString("usuario");

            // Compara a senha digitada com a senha do banco usando .equals()
            if (senhaDigitada.equals(senhaDoBanco)) {
                
                // SALVA OS DADOS NAS VARIÁVEIS DA SESSÃO
                InfoSessao.usuarioLogado = usuarioDoBanco;
                InfoSessao.senhaLogada = senhaDoBanco;
                
                JOptionPane.showMessageDialog(null, "Login realizado com sucesso! Bem-vindo, " + usuarioDoBanco + ".");
                
                // CÓDIGO PARA ABRIR A PRÓXIMA TELA (Exemplo):
                TelaInicial tela = new TelaInicial();
                tela.setVisible(true);
                this.dispose(); // Fecha a tela de login atual
                
            } else {
                JOptionPane.showMessageDialog(null, "Senha incorreta!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Usuário não cadastrado no sistema.");
        }

        // Fecha os recursos de leitura
        rs.close();
        stmtBuscar.close();
        conn.close();

    } catch(Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Erro ao tentar realizar login: " + e.getMessage());
    }
}
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
    /* Set the FlatLaf Dark look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If FlatLaf Dark is not available, stay with the default look and feel. */
    try {
        // Define diretamente a classe do FlatLaf Dark utilizando o gerenciador padrão do Swing
        javax.swing.UIManager.setLookAndFeel("com.formdev.flatlaf.FlatDarkLaf");
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(telaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(telaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(telaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(telaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new telaLogin().setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
