package Alunos;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author guest.jb
 */
public class NotaAluno extends javax.swing.JFrame {

    
    public NotaAluno() {
        initComponents();
        try {
    // Abre a conexão usando a sua classe de conexão
    Connection conn = conexao.conexao.conectar();

    // Limpa os itens antigos da combo box para não duplicar
    cbxAluno.removeAllItems();

    // Comando SQL para buscar os usuários
    String Sql = "select nome from alunos order by nome asc;";

    PreparedStatement stmt = conn.prepareStatement(Sql);
    
    // Executa a consulta e guarda os resultados no ResultSet
    ResultSet rs = stmt.executeQuery();

    // Percorre todos os usuários encontrados no banco
    while (rs.next()) {
        // Pega o texto da coluna "usuario" e adiciona na cbxUsuario
        cbxAluno.addItem(rs.getString("nome"));
    }

    // Fecha os recursos na ordem correta
    rs.close();
    stmt.close();
    conn.close();
    
} catch(Exception e) {
    e.printStackTrace();
}
        try {
    // Abre a conexão usando a sua classe de conexão
    Connection conn = conexao.conexao.conectar();

    // Cria o modelo para poder manipular os itens da JList de notas
    DefaultListModel<String> modeloLista = new DefaultListModel<>();

    // Pega o nome do aluno selecionado na ComboBox
    String nomeAlunoSelecionado = cbxAluno.getSelectedItem().toString();

    // Comando SQL que junta alunos e notas filtrando pelo nome do aluno selecionado
    String Sql = "SELECT n.nota FROM notas n " +
                 "INNER JOIN alunos a ON n.aluno_id = a.id " +
                 "WHERE a.nome = ?;";

    PreparedStatement stmt = conn.prepareStatement(Sql);
    // Substitui o primeiro '?' pelo nome do aluno selecionado
    stmt.setString(1, nomeAlunoSelecionado);
    
    // Executa a consulta e guarda os resultados no ResultSet
    ResultSet rs = stmt.executeQuery();

    double somaNotas = 0;
    int totalNotas = 0;

    // Percorre todas as notas encontradas para esse aluno
    while (rs.next()) {
        double nota = rs.getDouble("nota");
        
        // Adiciona a nota formatada como texto no modelo da JList
        modeloLista.addElement(String.valueOf(nota));
        
        // Acumula os valores para calcular a média depois
        somaNotas += nota;
        totalNotas++;
    }

    // Aplica o modelo preenchido na sua JList de notas (atualiza a interface)
    lstNotas.setModel(modeloLista);

    // Calcula a média e atualiza o lblMedia (evita divisão por zero se não houver notas)
    if (totalNotas > 0) {
        double media = somaNotas / totalNotas;
        lblMedia.setText(String.format("%.2f", media));
    } else {
        lblMedia.setText("0.00");
    }

    // Fecha os recursos na ordem correta
    rs.close();
    stmt.close();
    conn.close();
    
} catch(Exception e) {
    e.printStackTrace();
    
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbxAluno = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNota = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstNotas = new javax.swing.JList<>();
        btnLancar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblMedia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("LANÇAR NOTAS");

        cbxAluno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAlunoActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome Aluno");

        jLabel3.setText("Nota");

        lstNotas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstNotas);

        btnLancar.setText("LANÇAR");
        btnLancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLancarActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        jButton2.setText("VOLTAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("MÉDIA:");

        lblMedia.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblMedia.setText("txtMedia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbxAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLancar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 107, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLancar)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(lblMedia))
                        .addGap(6, 6, 6)))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnLancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLancarActionPerformed
    
        
        String Aluno = (String) cbxAluno.getSelectedItem();
        String alunoIdStr = "";
        try{ Connection conn = conexao.conexao.conectar();
        
            String sqlBuscaId = "SELECT id FROM alunos WHERE nome = ?";
            PreparedStatement stmtBusca = conn.prepareStatement(sqlBuscaId);
            stmtBusca.setString(1, Aluno);
            ResultSet rsBusca = stmtBusca.executeQuery();
            
            if (rsBusca.next()) {
                // Guarda o ID como String
                alunoIdStr = rsBusca.getString("id");
            }
    
    String sql="INSERT INTO notas (aluno_Id,nota) VALUES (?,?)";
    
    PreparedStatement stmt = conn.prepareStatement(sql);
    
    stmt.setString(1,alunoIdStr);
    stmt.setString(2,txtNota.getText());
    JOptionPane.showMessageDialog(null, "Salvo!");
    stmt.execute();
    stmt.close();
    conn.close();   
    }catch(Exception e){
            e.printStackTrace();
}
        try {
    // Abre a conexão usando a sua classe de conexão
    Connection conn = conexao.conexao.conectar();

    // Cria o modelo para poder manipular os itens da JList de notas
    DefaultListModel<String> modeloLista = new DefaultListModel<>();

    // Pega o nome do aluno selecionado na ComboBox
    String nomeAlunoSelecionado = cbxAluno.getSelectedItem().toString();

    // Comando SQL que junta alunos e notas filtrando pelo nome do aluno selecionado
    String Sql = "SELECT n.nota FROM notas n " +
                 "INNER JOIN alunos a ON n.aluno_id = a.id " +
                 "WHERE a.nome = ?;";

    PreparedStatement stmt = conn.prepareStatement(Sql);
    // Substitui o primeiro '?' pelo nome do aluno selecionado
    stmt.setString(1, nomeAlunoSelecionado);
    
    // Executa a consulta e guarda os resultados no ResultSet
    ResultSet rs = stmt.executeQuery();

    double somaNotas = 0;
    int totalNotas = 0;

    // Percorre todas as notas encontradas para esse aluno
    while (rs.next()) {
        double nota = rs.getDouble("nota");
        
        // Adiciona a nota formatada como texto no modelo da JList
        modeloLista.addElement(String.valueOf(nota));
        
        // Acumula os valores para calcular a média depois
        somaNotas += nota;
        totalNotas++;
    }

    // Aplica o modelo preenchido na sua JList de notas (atualiza a interface)
    lstNotas.setModel(modeloLista);

    // Calcula a média e atualiza o lblMedia (evita divisão por zero se não houver notas)
    if (totalNotas > 0) {
        double media = somaNotas / totalNotas;
        lblMedia.setText(String.format("%.2f", media));
    } else {
        lblMedia.setText("0.00");
    }

    // Fecha os recursos na ordem correta
    rs.close();
    stmt.close();
    conn.close();
    
} catch(Exception e) {
    e.printStackTrace();
    
}
    }//GEN-LAST:event_btnLancarActionPerformed

    private void cbxAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAlunoActionPerformed
        String Aluno = (String) cbxAluno.getSelectedItem();
        String alunoIdStr = "";
       
        try {
    // Abre a conexão usando a sua classe de conexão
    Connection conn = conexao.conexao.conectar();

    // Cria o modelo para poder manipular os itens da JList de notas
    DefaultListModel<String> modeloLista = new DefaultListModel<>();

    // Pega o nome do aluno selecionado na ComboBox
    String nomeAlunoSelecionado = cbxAluno.getSelectedItem().toString();

    // Comando SQL que junta alunos e notas filtrando pelo nome do aluno selecionado
    String Sql = "SELECT n.nota FROM notas n " +
                 "INNER JOIN alunos a ON n.aluno_id = a.id " +
                 "WHERE a.nome = ?;";

    PreparedStatement stmt = conn.prepareStatement(Sql);
    // Substitui o primeiro '?' pelo nome do aluno selecionado
    stmt.setString(1, nomeAlunoSelecionado);
    
    // Executa a consulta e guarda os resultados no ResultSet
    ResultSet rs = stmt.executeQuery();

    double somaNotas = 0;
    int totalNotas = 0;

    // Percorre todas as notas encontradas para esse aluno
    while (rs.next()) {
        double nota = rs.getDouble("nota");
        
        // Adiciona a nota formatada como texto no modelo da JList
        modeloLista.addElement(String.valueOf(nota));
        
        // Acumula os valores para calcular a média depois
        somaNotas += nota;
        totalNotas++;
    }

    // Aplica o modelo preenchido na sua JList de notas (atualiza a interface)
    lstNotas.setModel(modeloLista);

    // Calcula a média e atualiza o lblMedia (evita divisão por zero se não houver notas)
    if (totalNotas > 0) {
        double media = somaNotas / totalNotas;
        lblMedia.setText(String.format("%.2f", media));
    } else {
        lblMedia.setText("0.00");
    }

    // Fecha os recursos na ordem correta
    rs.close();
    stmt.close();
    conn.close();
    
} catch(Exception e) {
    e.printStackTrace();
   
}
    }//GEN-LAST:event_cbxAlunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotaAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLancar;
    private javax.swing.JComboBox<String> cbxAluno;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMedia;
    private javax.swing.JList<String> lstNotas;
    private javax.swing.JTextField txtNota;
    // End of variables declaration//GEN-END:variables
}
